<div id="test-container">
  <div id="watcher" data-lu="Abstract">
    <ul id="A" data-lu="List">
      <li id="larry" class="larry lu-state-selected">Larry</li>
      <li class="moe">
        <button id="moe-select" data-lu="Button:Select">Moe</button>
        <button id="larry-select_button" data-lu="Button:Select" aria-controls="larry">Larry</button>
        <a id="larry-select_anchor" data-lu="Button:Select" href="#larry">Larry</a>
      </li>
      <li class="curly">Curly</li>
    </ul>
    <ul id="B" data-lu="List">
      <li class="larry">Larry</li>
      <li class="moe lu-state-selected">Moe</li>
      <li class="curly">Curly</li>
    </ul>
    <ul id="C" data-lu="List">
      <li class="larry">Larry</li>
      <li class="moe">Moe</li>
      <li class="curly lu-state-selected">Curly</li>
    </ul>
  </div>
</div>
